Description: >
  Pablo Osinaga / Cloud DevOps Udacity nano degree

Parameters:
  ApplicationName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  InstanceType:
    Description: EC2 Instance type for the replica set
    Type: String
  ImageId:
    Description: Image Id for the EC2 instances
    Type: String
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16

Resources:
  JenkinsSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins
      GroupName: JenkinsSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  JenkinsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "test"
      ImageId: !Sub "${ImageId}"
      InstanceType: !Sub "${InstanceType}"
      SecurityGroups:
        - Ref: JenkinsSecGroup
      Tags:
        - Key: App
          Value: !Sub "${ApplicationName}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Step 1 - Update existing packages
          apt-get update -y
          # Step 2 - Install Java
          apt install -y default-jdk
          # Step 3 - Download Jenkins package.
          # You can go to http://pkg.jenkins.io/debian/ to see the available commands
          # First, add a key to your system
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
          # # Step 4 - Add the following entry in your /etc/apt/sources.list:
          sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          # # Step 5 -Update your local package index
          apt-get update -y
          # Step 6 - Install Jenkins
          apt-get install -y jenkins
          # Step 7 - Start the Jenkins server
          systemctl start jenkins
          # Step 8 - Enable the service to load during boot
          systemctl enable jenkins
          systemctl status jenkins
          # Step 9 - Install extra libraries
          apt install -y tidy
