Description: >
  Pablo Osinaga / Udagram project

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  PolicyName:
    Description: Name of the IAM policy
    Type: String

Resources:
  S3Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref EnvironmentName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: !Ref PolicyName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  S3InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref S3Role
Outputs:
  RoleName:
    Description: A reference to the created role
    Value: !Ref S3InstanceProfile
    Export:
      Name: !Sub ${EnvironmentName}-IAM-IP
