apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-k8s
  labels:
    app: udacity-ml-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-ml-k8s
  template:
    metadata:
      labels:
        app: udacity-ml-k8s
    spec:
      containers:
        - name: ml-k8s
          image: paguos/udacity-ml-k8s:v0.1.0
          ports:
            - containerPort: 80
